#
#  Copyright (c) 2019 Network Flex Any Comp. and others and others.  All rights reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at http://www.eclipse.org/legal/epl-v10.html
#

api-version=v1.0.3.3
controller-version=v1.0.3.3
supported-adapter-api-version=v1.0.3.3
is-check-adapter-version=true
regionId=1