<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>otdr-manager</artifactId>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>otdr-common</artifactId>
        <groupId>net.flex.dci.otn</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>otdr-core</artifactId>
        <groupId>net.flex.dci.otn</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>otdr-rest</artifactId>
        <groupId>net.flex.dci.otn</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>webapp</artifactId>
        <groupId>net.flex.dci.otn.controller.tools</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>fastjson</artifactId>
        <groupId>com.alibaba</groupId>
        <version>1.2.80</version>
      </dependency>
      <dependency>
        <artifactId>zkclient4boot</artifactId>
        <groupId>net.flex.dci.otc.zk</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>rpc-client</artifactId>
        <groupId>net.flex.dci.otn</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>db-mongo</artifactId>
        <groupId>net.flex.dci.otc</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>db-mysql</artifactId>
        <groupId>net.flex.dci.otc</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>netconf-serialization</artifactId>
        <groupId>net.flex.dci.otc</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>common-util</artifactId>
        <groupId>net.flex.dci.otc.common</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>common-model</artifactId>
        <groupId>net.flex.dci.otc.common</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>guava</artifactId>
        <groupId>com.google.guava</groupId>
        <scope>compile</scope>
        <version>30.1.1-jre</version>
      </dependency>
      <dependency>
        <artifactId>kafka</artifactId>
        <groupId>net.flex.dci.otn.controller.tools</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <artifactId>scanner-port-helper</artifactId>
        <groupId>net.flex.dci.otn</groupId>
        <version>1.0.0-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <modelVersion>4.0.0</modelVersion>
  <modules>
    <module>otdr-common</module>
    <module>otdr-core</module>
    <module>otdr-rest</module>
  </modules>
  <packaging>pom</packaging>

  <parent>
    <artifactId>controller</artifactId>
    <groupId>net.flex.dci.otn</groupId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
  </properties>

</project>