<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>controller</artifactId>
    <groupId>net.flex.dci.otn</groupId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <version>1.0.0-SNAPSHOT</version>
  <artifactId>user-manager</artifactId>

  <properties>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>net.flex.dci.otn.controller.tools</groupId>
      <artifactId>webapp</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>net.flex.dci.otc</groupId>
      <artifactId>db-mysql</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-crypto</artifactId>
    </dependency>
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
      <version>1.2.80</version>
    </dependency>
    <dependency>
      <groupId>net.flex.dci.otc.zk</groupId>
      <artifactId>zkclient4boot</artifactId>
    </dependency>
    <dependency>
      <groupId>net.flex.dci.otc.cache</groupId>
      <artifactId>dci-cache</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <exclusions>
      <exclusion>
      <groupId>net.flex.dci.otc</groupId>
      <artifactId>db-mongo</artifactId>
      </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>net.flex.dci.otn.controller.tools</groupId>
      <artifactId>kafka</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/application*.yml</include>
          <include>zkclient_conf.properties</include>
          <include>logback-spring.xml</include>
          <include>mysql.properties</include>
          <include>cache.properties</include>
          <include>tag-info</include>
        </includes>
      </resource>
    </resources>


    <plugins>
      <plugin>
        <!-- curl http://localhost:8080/actuator/info to get git info-->
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>4.9.10</version>
        <executions>
          <execution>
            <goals>
              <goal>revision</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>net.flex.dci.otc.plugin</groupId>
        <artifactId>systemd-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>


  <profiles>
    <profile>
      <id>product</id>
      <build>
        <plugins>

          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
          </plugin>

          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
          </plugin>

          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
          </plugin>

        </plugins>
      </build>
    </profile>
  </profiles>
</project>
