server:
  port: 19009

logging.level.net.flex.dci.otn.controller.cli: debug

---
spring:
  config:
    activate:
      on-profile: default

---
spring:
  config:
    activate:
      on-profile: production