<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~  Copyright (c) 2019 Network Flex Any Comp. and others and others.  All rights reserved.
  ~
  ~  This program and the accompanying materials are made available under the
  ~  terms of the Eclipse Public License v1.0 which accompanies this distribution,
  ~  and is available at http://www.eclipse.org/legal/epl-v10.html
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>net.flex.dci.otn</groupId>
    <artifactId>controller</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <groupId>net.flex.dci.otn.controller.allocate</groupId>
  <artifactId>alloc-designer</artifactId>
  <name>alloc-designer</name>
  <description>provide NE card info for config topo</description>

  <dependencies>

    <dependency>
      <groupId>net.flex.dci.otc.nbi</groupId>
      <artifactId>nbi-api-view</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>net.flex.dci.otn.controller.allocate</groupId>
      <artifactId>ne</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>net.flex.dci.otn.controller.allocate</groupId>
      <artifactId>alloc-common</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-csv</artifactId>
      <version>2.8.1</version>
    </dependency>
    <!--    <dependency>-->
    <!--      <groupId>org.apache.commons</groupId>-->
    <!--      <artifactId>commons-csv</artifactId>-->
    <!--      <version>1.5</version>-->
    <!--    </dependency>-->

    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.hamcrest</groupId>
          <artifactId>hamcrest-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
        </exclusion>
      </exclusions>
      <scope>test</scope>
      <!--      <version>2.2.6.RELEASE</version>-->
    </dependency>
    <dependency>
      <groupId>net.flex.dci.otc</groupId>
      <artifactId>db-mongo</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>net.flex.dci.otc.common</groupId>
      <artifactId>common-util</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>

    <!--    <dependency>-->
    <!--    <groupId>net.flex.dci.otn.controller.allocate</groupId>-->
    <!--    <artifactId>common</artifactId>-->
    <!--      <version>1.0.0-SNAPSHOT</version>-->
    <!--    </dependency>-->
    <!-- <dependency>
       <groupId>net.flex.dci.otn.controller.allocate</groupId>
       <artifactId>common</artifactId>
       <version>1.0.0-SNAPSHOT</version>
     </dependency>-->

  </dependencies>
</project>
