<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>controller</artifactId>
        <groupId>net.flex.dci.otn</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>nms-service</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>nms-common</module>
        <module>nms-cache</module>
        <module>nms-tree</module>
        <module>nms-rest</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <name>nms-service</name>
    <version>1.0.0-SNAPSHOT</version>
    <description>nms service for otn network</description>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.flex.dci.otn</groupId>
                <artifactId>nms-rest</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otn</groupId>
                <artifactId>nms-service</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otn</groupId>
                <artifactId>nms-tree</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otn</groupId>
                <artifactId>nms-common</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otc</groupId>
                <artifactId>db-mongo</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otn</groupId>
                <artifactId>rpc-client</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otc</groupId>
                <artifactId>netconf-serialization</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otc.common</groupId>
                <artifactId>common-model</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otc.common</groupId>
                <artifactId>common-util</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>1.2.80</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otc.cache</groupId>
                <artifactId>dci-cache</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>net.flex.dci.otn</groupId>
                <artifactId>nms-cache</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>