#
#  Copyright (c) 2019 Network Flex Any Comp. and others and others.  All rights reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at http://www.eclipse.org/legal/epl-v10.html
#

kafka.bootstrap-servers=135.251.96.62:9092
kafka.partition-number=5
kafka.replication-factor=1

#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%p] (%C:%L) : %m%n
logging.level.root=INFO
logging.level.com.nokia=DEBUG

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%p] (%C:%L) : %m%n

logging.file.max-size=10MB
logging.file.name=./logs/controller.logs
logging.pattern.rolling-file-name=${logging.file.name}.%d{yyyy-MM-dd}.%i.gz