###################################################################
######################## OAuth2 Registered Client #################
###################################################################
oauth2.registered.client.password.id=password-dci
oauth2.registered.client.password.name=password-client-name
oauth2.registered.client.password.secret=dciWorld
oauth2.registered.client.password.scope=all

