server:
  port: @port.discover@
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
---
spring:
  config:
    activate:
      on-profile: default
logging:
  level:
    net.flex.dci: debug
    org.springframework: OFF
    com.mongodb: OFF
    org.apache: OFF
    org.mongodb: OFF
    org.opendaylight: OFF
kafka:
  bootstrap-servers: 10.242.111.39:9092
  replication-factor: 1
---
spring:
  config:
    activate:
      on-profile: production
kafka:
  bootstrap-servers: ${KAFKA_BROKER}
  replication-factor: 1
logging:
  level:
    net.flex.dci: info
    org.springframework: OFF
    com.mongodb: OFF
    org.apache: OFF
    org.mongodb: OFF
    org.opendaylight: OFF
