#
#  Copyright (c) 2019 Network Flex Any Comp. and others and others.  All rights reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at http://www.eclipse.org/legal/epl-v10.html
#

#
# /*
#  *
#  * This program and the accompanying materials are made available under the
#  * terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  * and is available at http://www.eclipse.org/legal/epl-v10.html
#  */
#
# enable cli command use mongodb to save/restore data from mongodb,default is true
mongodb.enable=true
# enable auto restore data from mongodb
mongodb.restore.auto.enable=true
#mongodb.ip=10.242.111.24
#mongodb.servers=n3:27017
mongodb.servers=10.242.111.29:27017,10.242.111.29:27018,10.242.111.29:27019,10.242.111.29:27020
#mongodb.servers=135.251.96.66:27017,135.251.96.69:27017,135.251.96.63:27017

#mongodb.port=27017
#mongodb.port=27017
# database name
#mongodb.database=sotn
mongodb.database=sotn
# snapshot frequency, default is 100. 100 stands for 100 changes happened in config-tree mongodb save once
mongodb.snapshot.freq=100
#mongodb.user=
mongodb.user=
mongodb.pwd=
#defalut is null(supported sha1,sha256,mongd-cr), other mechanism supported SHA-1,SHA-256,MONGODB-CR,X-509,PLAIN,GSSAPI
#mongodb.mechanism = sha-1
#connection timeout, milliseconds.default is 120000
mongodb.client.option.connectTimeout=120000
# maximum life time for a pooled connection,milliseconds,default is 300000
mongodb.client.option.maxConnectionLifeTime=300000
# maximum idle life time for a pooled connection,milliseconds,default is 10000
mongodb.client.option.maxConnectionIdleTime=10000
# maximum number of connections per host,default is 10
mongodb.client.option.connectionsPerHost=10
