export MALLOC_ARENA_MAX=2
export JAVA_OPTS="-server -Xmx256m -Xms256m -XX:+UseG1GC -XX:MaxMetaspaceSize=128m -XX:MetaspaceSize=96m -XX:TieredStopAtLevel=1 -XX:CICompilerCount=2 -XX:NativeMemoryTracking=off -XX:+PrintGCDetails"
