<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~  Copyright (c) 2019 Network Flex Any Comp. and others and others.  All rights reserved.
  ~
  ~  This program and the accompanying materials are made available under the
  ~  terms of the Eclipse Public License v1.0 which accompanies this distribution,
  ~  and is available at http://www.eclipse.org/legal/epl-v10.html
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>batchlock-parent</artifactId>
        <groupId>net.flex.dci.otn.controller.batchlock</groupId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>batchlock-lib</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jdk.version>1.8</jdk.version>
        <jupiter.version>5.7.0</jupiter.version>
        <test-containers.version>1.14.3</test-containers.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.flex.dci.otn.controller.batchlock</groupId>
            <artifactId>batchlock-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.flex.dci.otn.controller.batchlock</groupId>
            <artifactId>batchlock-provider-zookeeper-curator</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.11</version>
        </dependency>
        <dependency>
            <groupId>net.flex.dci.otc.zk.common</groupId>
            <artifactId>zk-model</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>3.17.2</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Automatic-Module-Name>
                                com.nokia.otc.cd.toop.base.batchlock.lib
                            </Automatic-Module-Name>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
